name: 'update-gitleaks'
author: 'dev-hato Development Team'
description: 'gitleaksをアップデートする'
inputs:
  github-token: # id of input
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - name: Update
      shell: bash
      if: github.event_name != 'pull_request' || github.event.action != 'closed'
      run: ${{ github.action_path }}/scripts/action/update.sh
    - uses: dev-hato/actions-diff-pr-management@128afc4203b4e391e03868be91c987b2ddba7ea5 # v1.1.12
      with:
        github-token: ${{ inputs.github-token }}
        branch-name-prefix: fix-version-gitleaks
        pr-title-prefix: gitleaksをアップデートしてあげたよ！
