name: "update-gitleaks"
author: "dev-hato Development Team"
description: "gitleaksをアップデートする"
inputs:
  github-token: # id of input
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "composite"
  steps:
    - name: Update
      shell: bash
      if: github.event_name != 'pull_request' || github.event.action != 'closed'
      run: ${{ github.action_path }}/scripts/action/update.sh
    - uses: dev-hato/actions-diff-pr-management@cc201e3df74a342983025c4e97b7216b4e77f9f1 # v2.0.0
      with:
        github-token: ${{ inputs.github-token }}
        branch-name-prefix: fix-version-gitleaks
        pr-title-prefix: gitleaksをアップデートしてあげたよ！
