name: 'update-gitleaks'
author: 'dev-hato Development Team'
description: 'gitleaksをアップデートする'
inputs:
  github-token: # id of input
    description: 'GITHUB_TOKEN'
    required: true
runs:
  using: "composite"
  steps:
    - name: Update
      shell: bash
      run: ${{ github.action_path }}/scripts/action/update.sh
    - uses: dev-hato/actions-diff-pr-management@v1.1.2
      with:
        github-token: ${{ inputs.github-token }}
        branch-name-prefix: fix-version-gitleaks
        pr-title-prefix: gitleaksをアップデートしてあげたよ！
