name: 'update-gitleaks'
author: 'dev-hato Development Team'
description: 'gitleaksをアップデートする'
inputs:
  github-token: # id of input
    description: 'GITHUB_TOKEN'
    required: true
  repo-name:
    description: 'Repository name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Update
      shell: bash
      run: |
        version=""

        for f in $(find .github/workflows -type f); do
          v="$(yq '.jobs.*.steps[].uses | select(. == "github/super-linter*")' "${f}" | sed -e 's/.*@//g')"
          if [ -n "${v}" ]; then
            version="${v}"
            break
          fi
        done

        curl "https://raw.githubusercontent.com/github/super-linter/${version}/TEMPLATES/.gitleaks.toml" > .gitleaks.toml
        yq -i ".repos[].rev = \"$(docker run --entrypoint gitleaks "github/super-linter:slim-${version}" version | sed -e 's/\r//g')\"" .pre-commit-config.yaml
    - uses: dev-hato/actions-diff-pr-management@v1.0.3
      with:
        github-token: ${{ inputs.github-token }}
        branch-name-prefix: fix-version-gitleaks
        pr-title-prefix: gitleaksをアップデートしてあげたよ！
        repo-name: ${{ inputs.repo-name }}
