---
name: github-actions-cache-cleaner
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 21 * * *" # 06:00 JST
  workflow_dispatch:
permissions: read-all
jobs:
  github-actions-cache-cleaner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: dev-hato/github-actions-cache-cleaner@78dfc8081c060920e224d2d97faac9c7dbd08142 # v0.0.49
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
