---
name: update-package
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  # npm installを実行し、package.jsonやpackage-lock.jsonに差分があればPRを作る
  update-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        if: github.event_name != 'pull_request' || github.event.action != 'closed'
        with:
          cache: npm
      - if: github.event_name != 'pull_request' || github.event.action != 'closed'
        run: npm install
      - uses: dev-hato/actions-diff-pr-management@7cc8ab103917849f6995064afae9f4cbcfd009ae # v1.1.13
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          branch-name-prefix: fix-package
          pr-title-prefix: package.jsonやpackage-lock.jsonを直してあげたよ！
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
